# File: azure-pipelines.yaml
# This is the top-level YAML file that will orchestrate the pipeline

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: pipeline-templates/build.yaml
  parameters:
      AdminPassword: default
      AdminTestPassword: default
